### ISSUE TITLE
Bug with Geodatalayers

### ISSUE THREAD

**Issue by Skerre** [SDG-AI-Lab/DSVI_Tool_v3#141]
Dear Experts!

I experienced an error in both, the published version and local runtime of the tool when clicking on the geodatalayers. This should trigger an event that queries the cell value of the WMS tile at the clicked position. 

The error looks like this in the console:
![Bug](https://user-images.githubusercontent.com/38685413/196728502-73bba26a-7ae2-48af-9da8-e1d312c1609d.PNG)

Thank you for working all of these out I know its tedious with the CORS alarms and all of these errors are really annoying :(

**Comment by andreiPro** [comment]
Hi Martin, Team,
Working on.

**Comment by Skerre** [comment]
@andreiPro thank you, as always...

**Comment by andreiPro** [comment]
You are welcome:)
