### ISSUE TITLE
Bug CORS-Geolayer: Fetch Legend does not work in deployed version

### ISSUE THREAD

**Issue by Skerre** [SDG-AI-Lab/DSVI_Tool_v3#157]
The Fetch layer method does work in the localhost version but not in the deployed version:

![image](https://user-images.githubusercontent.com/38685413/197713500-e203e421-9bba-4cbe-9b25-00a3c247b44b.png)

**Comment by fpenarru** [comment]
Legend request is using IP instead of www.sdglab.ml
We should change it in order to avoid problems (GitHub Pages doesn't allow to make non https requests)
