### ISSUE TITLE
InfoBox should be triggered when opening a layer

### ISSUE THREAD

**Issue by Skerre** [SDG-AI-Lab/DSVI_Tool_v3#176]
When user clicks

on 

1) "show vulnerability" - INFO BOX opens with "Vulnerability information" section opened.

2) "Socioeconomic and Geodatalayers": 

When user opens a layer, it will trigger and open the Infobox and jump to the corresponding section of the Infobox.

![forinfobox](https://user-images.githubusercontent.com/38685413/199587592-ca6021e9-d893-4fd7-96eb-1d52b5013583.PNG)

**Comment by andreiPro** [comment]
Hi Martin,

**Comment by cadlec** [comment]
Hello sir Martin, hello everyone, 
Bug fixed sir Martin, please check my PR

**Comment by Skerre** [comment]
@cadlec 
dear Vital, thank you, I merged it!

**Comment by cadlec** [comment]
Hello sir Martin, thank you
