### ISSUE TITLE
InfoBox.js - buttons and infobox entangled

### ISSUE THREAD

**Issue by Skerre** [SDG-AI-Lab/DSVI_Tool_v3#181]
Dear Volunteers,

one thing I noticed and I am not sure if this is optimal:
The InfoBox.js file should control the mechanisms sorrounding the Infobox.
I would say its better to keep only the elements regarding the infobox inside this file, however we find 2 additional features in it:

1) There is a reference to a button, which is currently commented out, but used to serve a purpose: The TOGGLE_SHOW_DATA button. This used to exist in order to show each value of each polygon of the socioeconomic layers, but currently is not implemented into the tool.
2) The Button to trigger the infobox is also embedded in this section and it seems really intertwined with the infobox itself.

Should we separate those functions and order Buttons in 1 file and the infobox in 1 other file instead?

Best,
Martin

**Comment by andreiPro** [comment]
Good morning Martin, Team,
Done.
I've split the big component ControlMenu on 2 components: InfoBox and
MapControls. Also fixed: dragging of InfoBox, List in InfoBox.

Please check PL #184.

https://github.com/SDG-AI-Lab/DSVI_Tool_v3/pull/184

**Comment by Skerre** [comment]
@andreiPro 

Thank you, this was important
