### ISSUE TITLE
Trigger infobox button on off will break info box dragging

### ISSUE THREAD

**Issue by Skerre** [SDG-AI-Lab/DSVI_Tool_v3#187]

**Comment by Skerre** [comment]
https://user-images.githubusercontent.com/38685413/200274143-1add4dd4-805b-49ee-b148-97a8a0aa10c2.mp4

**Comment by andreiPro** [comment]
Hello Martin, Vital, Team,
Working on.

**Comment by andreiPro** [comment]
Martin,
Bug is fixed. 

https://github.com/SDG-AI-Lab/DSVI_Tool_v3/pull/189
