### ISSUE TITLE
InfoBox Action on click

### ISSUE THREAD

**Issue by Skerre** [SDG-AI-Lab/DSVI_Tool_v3#188]

**Comment by andreiPro** [comment]
Good morning Martin,
Can you please advise the description of task?

Thank you.

**Comment by Skerre** [comment]
@andreiPro Thank you for reaching out. I forgot to add the description.

The dropdown menu is for the socioeconomic layers.

![image](https://user-images.githubusercontent.com/38685413/200838881-3dbd940c-c19e-4ebb-8b20-7e5f0d075633.png)

When the user clicks on "Show vulnerability" it should show in the infobox the item called "Social Vulnerability"
(Maybe we need some landing page for the infobox), where we have like "Hello Welcome! This is the DSVI Tool!"

For "Methods" I will explain some details about how we calculated scores etc.

But it should something else.

So I think we need only the dropdown for socioeconomic / geodatalayers

**Comment by Skerre** [comment]
Hi @andreiPro do you think I should make a more detailed description?

**Comment by andreiPro** [comment]
Hi Martin,
Do I understand correctly that this should work like on the image below?
Will the dropdown menu be replaced with "New Landing Page" for Vulnerability?
Thank you.
<img width="1059" alt="Screen Shot 2022-11-13 at 3 44 45 PM" src="https://user-images.githubusercontent.com/64378048/201546496-995368d2-e09b-42b0-95fe-e12e823ff0d5.png">

**Comment by Skerre** [comment]
Yes Andrei!

**Comment by Skerre** [comment]
Ok Andrei I am merging. It looks good. Just one more thing for later: When clicking "reset" tool, maybe the view also snap back to the original position? Otherwise it looks good for now. Thank you I think this was much work

**Comment by andreiPro** [comment]
> Ok Andrei I am merging. It looks good. Just one more thing for later: When clicking "reset" tool, maybe the view also snap back to the original position? Otherwise it looks good for now. Thank you I think this was much work
> 

Hi Martin,
Thank you. 

When clicking "reset" tool, maybe the view also snap back to the original position? 
// Ok. No problem. I will do it.

**Comment by andreiPro** [comment]
Good morning Martin,
Done.
https://github.com/SDG-AI-Lab/DSVI_Tool_v3/pull/203

**Comment by Skerre** [comment]
@andreiPro  @rumessa 

Dear Andrei, Rumessa is working on these changes to the box - I consulted with her about the specifics.

**Comment by andreiPro** [comment]
Hi Martin,
Ok. No problem.
