### ISSUE TITLE
Drag and Drop does not really work anymore

### ISSUE THREAD

**Issue by Skerre** [SDG-AI-Lab/DSVI_Tool_v3#193]
Hello,

the layer should stay where the user puts it.

https://user-images.githubusercontent.com/38685413/201070675-6300986f-8daa-4238-89d4-fc5411111ba0.mp4

**Comment by cadlec** [comment]
Hello sir Martin, 
Ok, let me fix it

**Comment by Skerre** [comment]
@cadlec Thank you, waiting for it :)

**Comment by Skerre** [comment]
@cadlec Dear Vital, how is the progress going?

**Comment by cadlec** [comment]
Hi dear Martin, it is almost finished. Sorry for the delay

**Comment by andreiPro** [comment]
Good morning Martin, Vital,
I've found solution, PR #221.
![new_](https://user-images.githubusercontent.com/64378048/204428067-d1926bb6-f06f-4815-9aaf-49dd3880f9ee.gif)

**Comment by cadlec** [comment]
Hello sir Martin and everyone, 
Thank you sir @andreiPro
