### ISSUE TITLE
Small design change to legend

### ISSUE THREAD

**Issue by Skerre** [SDG-AI-Lab/DSVI_Tool_v3#196]
Dear Andrei,

could we make a small change to the legends?

![legend_update](https://user-images.githubusercontent.com/38685413/201082918-dff19310-ba19-4bce-ad3b-fc23589287cd.PNG)

**Comment by andreiPro** [comment]
Good morning Martin,
Ok. No problem.

**Comment by Skerre** [comment]
@andreiPro Thank you
