### ISSUE TITLE
Value Sensitive Legend

### ISSUE THREAD

**Issue by Skerre** [SDG-AI-Lab/DSVI_Tool_v3#30]
We have 3 different types of data:

Vector layers (embedded as json) (see image attached)
The values of the vector layers are currently 
Point layers
GeoTiff rendered images

We need legend describing the value space of each layer and the selected data inside it.

![image](https://user-images.githubusercontent.com/38685413/173044880-192d3e72-0eeb-4ca2-aa0c-d6c3480c6091.png)

**Comment by andreiPro** [comment]
HI Martin,
I've just sent the pull request 'SocioeconomicLayers_Legend #91'.
1st part/section (Socioeconomic Layers) is ready.
<img width="1430" alt="Screen Shot 2022-10-04 at 6 56 32 PM" src="https://user-images.githubusercontent.com/64378048/193951826-9b987cb6-e3a3-4bdb-adb6-670a38f24570.png">

**Comment by andreiPro** [comment]
Hi Martin,
Is it valid task?

Thank you.
