### ISSUE TITLE
Include csv file for 'Show DHS data' button in the menu

### ISSUE THREAD

**Issue by Skerre** [SDG-AI-Lab/DSVI_Tool_v3#38]

**Comment by Skerre** [comment]
@imsakararyal 
@lordakarias 
@SmoothMaverick 

please have a look, this one is quite straight forward I think:

The functionality looks like this:

The CSV file contains columns which represent variables we want to visualize. 
Each row is a point and contains corresponding [lat, lon] coordinates.

![image](https://user-images.githubusercontent.com/38685413/178051526-77a9a116-6ca9-4d05-b9a0-0de39778acc2.png)

This is how it should look like in the application:

1. User selects "Show DHS indicator"
2. Wind popup: "Select Column"
3. User can select column
4. User then confirms with OK
5. System loads values from CSV file and corresponding column on map
6. Legend appears and shows value and color range
7. Each row in the csv file is = 1 point on the map (lat lon)
8. Color code is predefined: We should use Blue Green Yellow Red to show "good to bad" or "high to low" "low to high"
9. When user hovers with mouse above point, point is showing infobox (such as in the gif below)

![DHS_indicator](https://user-images.githubusercontent.com/38685413/178043344-e4ac7083-c47b-4572-9d43-1c9fb0d3c985.gif)

**Comment by Skerre** [comment]
The image is a gif, click on it to see it in action

**Comment by SmoothMaverick** [comment]
Can you provide the CSV file?

**Comment by cadlec** [comment]
Hello everyone
Please @Skerre can you provide us the CSV file? or is there an API where we can fetch the data?

Thanks

**Comment by Skerre** [comment]
Dear Vital
[demotool_data.csv](https://github.com/SDG-AI-Lab/DSVI_Tool_v3/files/9336732/demotool_data.csv)

**Comment by cadlec** [comment]
Thank you sir Martin

**Comment by DKdEviL** [comment]
@Skerre I have completed upto this (refer to the video attached). I have one question, **Is it ok to put the CSV file into public/static folder?**


https://user-images.githubusercontent.com/38316396/184954125-7e9416e9-f951-4176-980c-227a4b865fe2.mp4

**Comment by Skerre** [comment]
Dear @DKdEviL 

Thank you for doing this so quickly. Yes, the menu should 'see' the available columns of the file.
This is the correct first step. 
Now, we need to display those points on the map, once the user selects one of the columns. 
You can place the file in public/static.

**Comment by cadlec** [comment]
Hello everyone
Please @Skerre, I've almost finished adding points on the map, but I'm struggling with colors. Is there a condition to know when CSV column data values are "good to bad",  "high to low" or "low to high"? Thanks.
![map-screen](https://user-images.githubusercontent.com/25343854/185201590-6c12d346-b937-42fb-b706-fe0bc38e5fc6.PNG)

**Comment by DKdEviL** [comment]
@cadlec Amazing work there

**Comment by Skerre** [comment]
@cadlec @DKdEviL 

Thanks both of you for the work so far. Both solutions go in the right direction: 

Now I am not sure if one of you actually implemented the point cloud on the map without the selection menu and other person the other way around, or if both implemented the selection menu? 



![image](https://user-images.githubusercontent.com/38685413/185344622-f5a58e08-e5e6-4700-844f-7bfb4b10e4f6.png)



If you have a working solution by now, we can immediately stop working on the same thing and I will split up the tasks so that nobody is working on the same thing at the same time.

Thank you both for coming up with quick solutions.

**Comment by DKdEviL** [comment]
@Skerre I would say me and @cadlec can connect and merge our codes, in that way the task will be completed as whole.

**Comment by Skerre** [comment]
Ok great. I will review that as a whole and approve merge request. Also, there might be some minor changes we need to take care of:

> Please @Skerre, I've almost finished adding points on the map, but I'm struggling with colors. Is there a condition to know when CSV column data values are "good to bad", "high to low" or "low to high"? Thanks 

 Can I parse you a json file or something else that explains you which way it should be colored?

**Comment by cadlec** [comment]
> @cadlec Amazing work there

Thank you @DKdEviL , you did amazing work too with the menu !

**Comment by cadlec** [comment]
> @cadlec @DKdEviL
> 
> Thanks both of you for the work so far. Both solutions go in the right direction:
> 
> Now I am not sure if one of you actually implemented the point cloud on the map without the selection menu and other person the other way around, or if both implemented the selection menu?
> 
> ![image](https://user-images.githubusercontent.com/38685413/185344622-f5a58e08-e5e6-4700-844f-7bfb4b10e4f6.png)
> 
> If you have a working solution by now, we can immediately stop working on the same thing and I will split up the tasks so that nobody is working on the same thing at the same time.
> 
> Thank you both for coming up with quick solutions.

Hello @Skerre , it seems @DKdEviL has done with the selection menu feature and I'm working on the maps' points

**Comment by cadlec** [comment]
> @Skerre I would say me and @cadlec can connect and merge our codes, in that way the task will be completed as whole.

Great idea @DKdEviL , thank you!

**Comment by cadlec** [comment]
> Ok great. I will review that as a whole and approve merge request. Also, there might be some minor changes we need to take care of:
> 
> > Please @Skerre, I've almost finished adding points on the map, but I'm struggling with colors. Is there a condition to know when CSV column data values are "good to bad", "high to low" or "low to high"? Thanks
> 
> Can I parse you a json file or something else that explains you which way it should be colored?

Yes @Skerre , I will appreciate it. A JSON file or something else would be great

**Comment by Skerre** [comment]
@cadlec

I am working on it and will share

**Comment by cadlec** [comment]
Thank you @Skerre!

**Comment by Skerre** [comment]
Dear @cadlec @DKdEviL 

This is a lookup table I created: 
[color_gradient_lookup.txt](https://github.com/SDG-AI-Lab/DSVI_Tool_v3/files/9374983/color_gradient_lookup.txt)

Some information about the file: 

1. You can rename it to .json or read it this way.
2. I added a column called 'BlueGreenYellowRed? (0=No;1=Yes)'. This means that if the value is 1, then we need the colormap 'Blue - Green - Yellow - Red', if we have 0 we need 'Red - Green - Yellow - Red', or simply the inverse of the other one. 
3. Sven is working on a way to colorcode the data here. I think we used hex colors.
4. The data in the dataframe is not normalized or standardized. So sometimes a value will be ranging from 0-1 and sometimes it can range between any two values, for example 1000-10000 (just an example). I guess, in order to apply a normalized way to colorcode values, we could use the MinMax normalization approach:
![image](https://user-images.githubusercontent.com/38685413/185428962-10b4412e-2c5a-452e-8bc1-39a0855da2b5.png)
You can have a look inside the code of the repo because I am sure that there is a function somewhere where we do this.

1. **Regarding Hover with mouse:** We want to show some info in that box: The value shown should be max 2 decimals. Also, we might want to access some additional information and display it, for example the column 'Urban Rural'. This can be adjusted later as well.

**Comment by DKdEviL** [comment]
@Skerre I have just shared all my changes with @cadlec so that he can add my changes with his changes and this task progress speeds up.

@cadlec Feel free to comment here or on slack if you need any other help with that.

**Comment by cadlec** [comment]
> 

Thank you @Skerre, I'll read it carefully!

**Comment by cadlec** [comment]
> @Skerre I have just shared all my changes with @cadlec so that he can add my changes with his changes and this task progress speeds up.
> 
> @cadlec Feel free to comment here or on slack if you need any other help with that.

Thanks @DKdEviL , I got them.

**Comment by cadlec** [comment]
Hello everyone, please @Skerre , I'm having an issue.
You said: _I added a column called 'BlueGreenYellowRed? (0=No;1=Yes)'. This means that if the value is 1, then we need the colormap 'Blue - Green - Yellow - Red', if we have 0 we need 'Red - Green - Yellow - Red', or simply the inverse of the other one._

Let's say there is a point where its "Average systolic blood pressure" is 0.75(after normalization).  Which color should be used knowing that for the "Average systolic blood pressure" the "BlueGreenYellowRed? (0=No;1=Yes)" = 1 ? 

Thanks

**Comment by Skerre** [comment]
Dear @cadlec thank you for your question.
First of all, it would mean that we apply it in order "BlueGreenYellowRed" where the values close to 0 are represented in a bluish hue and the maxima (near 1) are in a reddish tone. Everything in between should be gradually changing (maybe in order of 10 color bins) from one color to another.
The gradient looks like this:

![parula_part_2_01](https://user-images.githubusercontent.com/38685413/185756072-84b5653c-7269-4438-ab0b-89e172dd777c.png)

Our previous volunteer I think had a similar approach already for polygon colors; you can find it in the file interact_map.txt (actually a .js file)
He implemented some polygon (instead of point) coloring scheme there using the colors



[interact_map.txt](https://github.com/SDG-AI-Lab/DSVI_Tool_v3/files/9388090/interact_map.txt)

**Comment by Skerre** [comment]
@cadlec If you guys need any help let me know and kindly let me know a timeline when i can expect your updates to be ready.
Best,
Martin

**Comment by cadlec** [comment]
Hello @Skerre, please excuse me for the late reply. Thanks for your help, I promise to finish by Friday

**Comment by cadlec** [comment]
Hello @Skerre , I've finished and made a PR.

https://user-images.githubusercontent.com/25343854/186661294-3b228bda-6a2f-4e94-8b87-cb23978036cb.mp4

**Comment by cadlec** [comment]
Sir @Skerre , I've fixed the build error, you can check it now
