### ISSUE TITLE
Sidebar adjustments

### ISSUE THREAD

**Issue by Skerre** [SDG-AI-Lab/DSVI_Tool_v3#42]
1. When we open a layer for example socioeconomic layer, the menu will expand in size for no apparent reason. Can we just fix the size of the sidebar to the size when it is expanded? So we would have to make it a bit wider than it is now. Something like 20 pixels I guess.

2. When we open new dropdown items in the menu like "geodatalayers", there is an ever increasing gap of nothingness below the map window because the sidebar is expanding in size but it is not scaling the map as well. I guess a solution could be to enable scrolling within the sidebar menu so it never changes its actual size compared to the map window, which is at the moment hard coded to be 800 px in height. I tried to make it 100% but it did not work as it does with the width.

3. We could add a Title header of the Sidebar called "Menu" in a slightly larger font but this is of secondary importance now.

![sidebar1](https://user-images.githubusercontent.com/38685413/182014913-24d6aff4-4b83-408c-968d-41aeeac8f166.gif)

![sidebar2](https://user-images.githubusercontent.com/38685413/182014916-667b3166-84bf-4757-bf55-2275af1f0741.gif)

**Comment by andreiPro** [comment]
Hi Martin,
All done:
1. Sidebar width & height is fixed;
2. Updated design of Map (no gaps);
3. Added title "Menu" in Sidebar. 

![Record](https://media.giphy.com/media/T4veguF0KJoN9IUMJL/giphy.gif)

**Comment by andreiPro** [comment]
I've sent the pull request.
