### ISSUE TITLE
Link WMS geoserver addresses to 'GeoLayer' submenu

### ISSUE THREAD

**Issue by Skerre** [SDG-AI-Lab/DSVI_Tool_v3#51]

**Comment by Skerre** [comment]
Implementation code example from previous app: 

var SSA1 = L.tileLayer.wms("http://129.151.248.181/geoserver/sdg-ai-lab/wms", {
        layers: "sdg-ai-lab:XGBoost_tuned_scaled_clipped_final",
        format: "image/png",
        transparent: true,
        version: "1.1.0",
        style: "sdg-ai-lab:xgboost",
    });

    var SSA2 = L.tileLayer.wms("http://129.151.248.181/geoserver/sdg-ai-lab/wms", {
        layers: "sdg-ai-lab:Random_Forest_tuned_scaled_clp_final",
        format: "image/png",
        transparent: true,
        version: "1.1.0",
        style: "sdg-ai-lab:xgboost",
    });

    var SSA3 = L.tileLayer.wms("http://129.151.248.181/geoserver/sdg-ai-lab/wms", {
        layers: "sdg-ai-lab:scaled_r_norm_NTL",
        format: "image/png",
        transparent: true,
        version: "1.1.0",
        style: "sdg-ai-lab:ntl_0_255_style"
    });

    var SSA4 = L.tileLayer.wms("http://129.151.248.181/geoserver/sdg-ai-lab/wms", {
        layers: "sdg-ai-lab:scaled_r_norm_cellt",
        format: "image/png",
        transparent: true,
        version: "1.1.0",
        style: "sdg-ai-lab:ntl_0_255_style"
    });

    var SSA5 = L.tileLayer.wms("http://129.151.248.181/geoserver/sdg-ai-lab/wms", {
        layers: "sdg-ai-lab:scaled_r_norm_edu_dd_spd_10k_4326",
        format: "image/png",
        transparent: true,
        version: "1.1.0",
        //style: "sdg-ai-lab:ntl_0_255_style"
    });

    var SSA6 = L.tileLayer.wms("http://129.151.248.181/geoserver/sdg-ai-lab/wms", {
        layers: "sdg-ai-lab:scaled_r_norm_finan_dd_spd_10k_4326",
        format: "image/png",
        transparent: true,
        version: "1.1.0",
        style: "sdg-ai-lab:ntl_0_255_style"
    });

    var SSA7 = L.tileLayer.wms("http://129.151.248.181/geoserver/sdg-ai-lab/wms", {
        layers: "	sdg-ai-lab:scaled_r_norm_health_dd_spd_10k",
        format: "image/png",
        transparent: true,
        version: "1.1.0",
        style: "sdg-ai-lab:ntl_0_255_style"
    });

    var SSA8 = L.tileLayer.wms("http://129.151.248.181/geoserver/sdg-ai-lab/wms", {
        layers: "sdg-ai-lab:scaled_r_norm_maxtemp_feb",
        format: "image/png",
        transparent: true,
        version: "1.1.0",
        style: "sdg-ai-lab:ntl_0_255_style"
    });
    var SSA9 = L.tileLayer.wms("http://129.151.248.181/geoserver/sdg-ai-lab/wms", {
        layers: "sdg-ai-lab:scaled_r_norm_pop",
        format: "image/png",
        transparent: true,
        version: "1.1.0",
        style: "sdg-ai-lab:ntl_0_255_style"
    });
    var SSA10 = L.tileLayer.wms("http://129.151.248.181/geoserver/sdg-ai-lab/wms", {
        layers: "sdg-ai-lab:scaled_r_norm_precip",
        format: "image/png",
        transparent: true,
        version: "1.1.0",
        style: "sdg-ai-lab:ntl_0_255_style"
    });
    var SSA11 = L.tileLayer.wms("http://129.151.248.181/geoserver/sdg-ai-lab/wms", {
        layers: "sdg-ai-lab:scaled_r_norm_road_density",
        format: "image/png",
        transparent: true,
        version: "1.1.0",
        style: "sdg-ai-lab:ntl_0_255_style"
    });
    var SSA12 = L.tileLayer.wms("http://129.151.248.181/geoserver/sdg-ai-lab/wms", {
        layers: "sdg-ai-lab:scaled_r_norm_rwi_heatmap_filled_final",
        format: "image/png",
        transparent: true,
        version: "1.1.0",
        style: "sdg-ai-lab:ntl_0_255_style"
    });
    var SSA13 = L.tileLayer.wms("http://129.151.248.181/geoserver/sdg-ai-lab/wms", {
        layers: "sdg-ai-lab:scaled_r_norm_slope",
        format: "image/png",
        transparent: true,
        version: "1.1.0",
        style: "sdg-ai-lab:ntl_0_255_style"
    });
    var SSA14 = L.tileLayer.wms("http://129.151.248.181/geoserver/sdg-ai-lab/wms", {
        layers: "sdg-ai-lab:scaled_r_norm_NDVI",
        format: "image/png",
        transparent: true,
        version: "1.1.0",
        style: "sdg-ai-lab:ntl_0_255_style"
    });
    var SSA15 = L.tileLayer.wms("http://129.151.248.181/geoserver/sdg-ai-lab/wms", {
        layers: "sdg-ai-lab:scaled_r_norm_GDP_2015_intp",
        format: "image/png",
        transparent: true,
        version: "1.1.0",
        style: "sdg-ai-lab:ntl_0_255_style"
    });
    var SSA16 = L.tileLayer.wms("http://129.151.248.181/geoserver/sdg-ai-lab/wms", {
        layers: "sdg-ai-lab:scaled_r_norm_DEM_Large",
        format: "image/png",
        transparent: true,
        version: "1.1.0",
        style: "sdg-ai-lab:ntl_0_255_style"
    });

    var additional_layers = [
        SSA1, // XGboost 1
        SSA2, // Random Forest 2
        SSA5, // edu 3
        SSA6, // finan 4
        SSA7, // health 5
        SSA12, // rwi 6
        SSA15, // gdp 7
        SSA3, // NTL 8
        SSA4, // cellt 9
        SSA9, // pop 10
        SSA11, // road 11
        SSA10, // precp 12
        SSA8, // maxtemp 13
        SSA14, // ndvi 14
        SSA13, // slope 15
        SSA16 // dem 16
    ];

    // Fixed: meaningful names
    var layer_names = [
        "XGBoost SV Prediction",
        "Random Forest SV Prediction",
        "Educational",
        "Financial",
        "Health",
        "Relative Wealth",
        "GPD Income",
        "Nightlight Intensity",
        "Celltower Density",
        "Population Density",
        "Road Density",
        "Precipitation",
        "Maximum Winter Temp",
        "Plant Health",
        "Slope",
        "Elevation"
    ];

**Comment by andreiPro** [comment]
Hi Martin,
Working on.

**Comment by Skerre** [comment]
Thank you @andreiPro
