### ISSUE TITLE
Show tooltip when hovering above buttons in map window

### ISSUE THREAD

**Issue by Skerre** [SDG-AI-Lab/DSVI_Tool_v3#52]
This idea is from the tool https://data.undp.org/sids/geospatial-data
which can be considered a benchmark tool for best practices.

![sidebar2](https://user-images.githubusercontent.com/38685413/185434695-a13c6d03-f158-4f23-beda-8224e33c551f.gif)

Also, I would like to change the current design of the buttons to be slightly larger and have a semi-transparent background in white.

**Comment by cadlec** [comment]
Hello @Skerre ok, thank you!

**Comment by cadlec** [comment]
Hello @Skerre , please can you provide me the images that are on these buttons? or can I download them on this website  https://data.undp.org/sids/geospatial-data ?

**Comment by Skerre** [comment]
Hi @cadlec,

lets use some dummy images (I am not sure what format they use, .jpg, .ico, .png?) for now, what I need is something closer to their style in terms of being slightly transparent and also stacked on top of each other on the map.
If you play the gif on top, you can see that a little description appears, when the user is hovering above the button. We would like to have this functionality. You can use a dummy text like "test hover button" for now and we can change the text later.

Thank you!

**Comment by cadlec** [comment]
Hello @Skerre Thank you. I get it.

**Comment by cadlec** [comment]
Hello sir @Skerre 
Sorry for the delay. It's good now, please check it.

https://user-images.githubusercontent.com/25343854/191827426-fe3311df-1c7e-4ce1-be08-b46412b1dc8f.mp4

**Comment by Skerre** [comment]
Thank you @cadlec
