### ISSUE TITLE
Data Button should trigger a info-box

### ISSUE THREAD

**Issue by Skerre** [SDG-AI-Lab/DSVI_Tool_v3#53]
We have a data-button which should trigger an info-box.

We would like to trigger a info box in a similar to the one found in SIDS data tool:

![image](https://user-images.githubusercontent.com/38685413/185443711-b8d0d9eb-ceb4-4867-b635-1d18f379af75.png)

![image](https://user-images.githubusercontent.com/38685413/185436242-b1c8335f-e870-46d6-b7db-bb29b4014a94.png)

**Comment by DKdEviL** [comment]
@Skerre Can I install npm package [React Dropdown](https://www.npmjs.com/package/react-dropdown) to implement this dropdown?

**Comment by DKdEviL** [comment]
Updates so far: 

Review and suggest any changes

![Info box](https://user-images.githubusercontent.com/38316396/187018449-ef5c9952-d837-4bee-8bff-8ee4859a0248.PNG)

**Comment by Skerre** [comment]
@DKdEviL Thank you so far. 

A few questions: 

1) Are we able to embed images?
2) Can we query the information for the box from active json files or active layers on the map?
3) In case multiple layers are active, can we let the user 'turn pages' or 'click on one of the selected layers in the grey area' to view the layer information?
4) Is this box movable / draggable, or resizable? 
5) Can we close the box?

Thank you so much, looking forward for your answers!

**Comment by DKdEviL** [comment]
@Skerre 

1. I will embed the images, once you give me green signal to use the above two npm package.
2. To get data from the json file, you need to point me to that specific json file (I am not able to understand the logic of layers, if you can elaborate, that would be great)
3. If by layers/pages you mean to select the layers from this dropdown field (attached image), then I can achieve that. Here is the image: 
![Capture](https://user-images.githubusercontent.com/38316396/187036598-03aec4a9-492c-4302-b3b8-4f823df5177a.PNG)

4. No, the box is not movable/draggable or resizable, but if you can give me a usecase to make it work in that way, then I can try.
5. Yes, box can be closed by clicking outside the infobox, I can show a close icon if you want.

**Comment by DKdEviL** [comment]
@Skerre After taking latest code, I see there is no button to trigger Info Box, the code is commented out, if we are not showing those 2 buttons, then how can we show this infoBox I am working upon.

Here is the image of running tool with latest code,
![Control Menu](https://user-images.githubusercontent.com/38316396/187037676-6f53ab2d-6f2f-487b-8fe7-bd7ab7e335ba.PNG)

**Comment by Skerre** [comment]
Dear @DKdEviL , the two buttons disappeared, but you can reactive them by uncommenting the lines in map.js

288-296

```
 <ControlMenu position="topRight" show_data={show_data} show_sidebar_data={show_sidebar_data}
          children={
            distance_to_healthcare_status || distance_to_healthcare_status || distance_to_healthcare_status ?
              <Legend />
              :
              null
          }
        >
        </ControlMenu>
```

but the variable names for 'children' were changed, you need to pick something existing now. otherwise the buttons wont show up anymore.

**Comment by Skerre** [comment]
> @Skerre Can I install npm package [React Dropdown](https://www.npmjs.com/package/react-dropdown) to implement this dropdown and [React Carousel](https://www.npmjs.com/package/react-responsive-carousel) for top-right carousel?

@DKdEviL we can try that and see if it works well for us!

**Comment by Skerre** [comment]
@DKdEviL 

> To get data from the json file, you need to point me to that specific json file (I am not able to understand the logic of layers, if you can elaborate, that would be great)

**Martin:** 

In a nutshell, we have 3 different types of data we show to users. 

1) Socioeconomic Layers (JSON files located under public/ static)
2) Geodata Layers (accessed via WMS from a server)
3) DHS Indicators (point data from a csv file)
Not implemented yet 4) Show the vulnerability as points.

Can we establish a mechanism which will be aware of the layers selected by a user (any of those 3 categories) and allows the user to view additional information about those layers? 

If a user selects some data for instance:

1) Socioeconomic Layers: 'DT: Education Facility' and
2) Show DHS Indicators: 'Average age of household head'

 ![image](https://user-images.githubusercontent.com/38685413/187446854-52fbd020-de1f-4fc5-8e32-a025b2b2021b.png)

The user should 'see', either in the info box, with text + images predefined information about the visible layers. things like data sources, explanation of the units used, maybe an image of a SDG relevant for this instance.
The dropdown menu could be used to navigate through the open layers. Or if that is difficult to implement, show all the existing layers and let the user decide which one he / she wants to learn more about.

Maybe we should actually implement a seperate button for this on top of the map, instead of on its side.

> No, the box is not movable/draggable or resizable, but if you can give me a usecase to make it work in that way, then I can try.

**Martin**: 

a) If we cannot make the box movable, then lets have it in one of the corners of the map window.
b) Also, it would be good if it would not 'grey out' the entire map, but be 'part of' the map itself.


> Yes, box can be closed by clicking outside the infobox, I can show a close icon if you want.

**Martin**: 

Yes that would be a good addition.

**Comment by Skerre** [comment]
reopened

**Comment by DKdEviL** [comment]
https://user-images.githubusercontent.com/38316396/188491975-08512aa0-7cc2-4a1d-823d-8ea8964137df.mp4

@Skerre Based on the information you mentioned above, this is how I understand it, please correct me if I am wrong. 
Also, feel free to schedule a call with me to discuss the information.

**Comment by Skerre** [comment]
@DKdEviL 
@salmiah-ls 
@andreiPro 

Could we make a first change to this and make this info box in a way that it does not grey out the whole window when triggered?
I guess it should be somewhere in the top left or bottom left. The content of this info box should be showing information about open layers.
This information will be hardcoded and read from the static folder.

![image](https://user-images.githubusercontent.com/38685413/193660098-66a9bf0b-9274-467c-81f2-3cc34fc220f7.png)
