### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by Skerre** [SDG-AI-Lab/DSVI_Tool_v3#70]

**Comment by Skerre** [comment]
![radar_landing_page](https://user-images.githubusercontent.com/38685413/187469282-ecd84239-8273-45e1-9d29-03be197393ad.PNG)

**Comment by cadlec** [comment]
Hello @Skerre 
Thank you for this task.
Please is this page the welcome page (or homepage) of the app? Have you any mockup of it?

**Comment by Skerre** [comment]
@cadlec I thought the image on top could help. I can answer you specific questions if needed!

**Comment by cadlec** [comment]
Ok sir @Skerre , can you give me the background image ?

**Comment by Skerre** [comment]
@cadlec please use this one for now
![background](https://user-images.githubusercontent.com/38685413/193276268-76e3acfa-fa08-41c4-b2a9-fa57c7dd0a98.jpeg)

**Comment by cadlec** [comment]
ok sir @Skerre thank you

**Comment by cadlec** [comment]
Hello sir @Skerre , please what do you think of this?
![image](https://user-images.githubusercontent.com/25343854/194059106-43fd2069-1bb8-4a2b-b4ab-881c61cc4003.png)

**Comment by Skerre** [comment]
Dear @cadlec it looks beautiful. Please send me a pull request :)

**Comment by cadlec** [comment]
Ok sir @Skerre , thanks !

**Comment by cadlec** [comment]
Hello sir Martin, I've made some improvements to the landing page, what do you think ?

![image](https://user-images.githubusercontent.com/25343854/194384874-c865e220-1bae-4973-878a-7320ea7c7a7d.png)

**Comment by Skerre** [comment]
Dear Vital, I really like this one already. But could we use the SDG AI LAB logo with White font? I attach it here :)
![Webp net-resizeimage](https://user-images.githubusercontent.com/38685413/194404867-61e5f195-a2de-4cea-90f9-9758a4ada3a2.png)

**Comment by cadlec** [comment]
Hello sir Martin, ok. Like this?
![image](https://user-images.githubusercontent.com/25343854/194531272-f38571a4-be42-4a67-97f8-cd54c6cd7cef.png)

**Comment by Skerre** [comment]
@cadlec Hello, maybe there is an issue with the .png file format but would it be possible to make the font of the SDG AI LAB logo white?
![sdg_ai_black_white_font](https://user-images.githubusercontent.com/38685413/194562480-1e7edf03-cc7b-4367-a359-4c78ded46e81.png)

**Comment by cadlec** [comment]
ok sir @Skerre 

![image](https://user-images.githubusercontent.com/25343854/194583392-30c37657-64d1-42c4-bb1e-2bc8581f7625.png)
