### ISSUE TITLE
Show Social Vulnerability Points

### ISSUE THREAD

**Issue by Skerre** [SDG-AI-Lab/DSVI_Tool_v3#77]

**Comment by Skerre** [comment]
I will add description

**Comment by andreiPro** [comment]
Hi Martin,
Ok. Thank you.

**Comment by Skerre** [comment]
My internet is super bad but I try to explain you what I need:

There is a file in the repo called 'SV_TJ_comp_1_4_Vulnerability_norm.csv'.  It contains vulnerability data for with lat / lon coordinates to visualize on a map.

When the user clicks the button 'Show Vulnerability' it should display these points on the map.
The points have an underlying vulnerability category in the column 'SV_scaled_cat'. You can use this and the corresponding levels 'Very Low', 'Low', 'Medium', 'High', 'Very High' and give them colors like this

![show_vulnerability](https://user-images.githubusercontent.com/38685413/189905461-c1ef9f19-7cc4-4cf3-b3e9-650961dc7859.PNG)

Also, it would be nice to actually see the colors like in the image next to the levels as in the example I uploaded to you.
Additionally, it would be great if the user could click and select the groups by checking each of the boxes.
The points on the map should have the same colors as in the menu legend (blue, green, yellow, orange, red). If the user hovers over a point, a tooltip should pop up (similar to the one we use in the socioeconomic layers) and give the user the following informational details:

Example:
Vulnerability: Low
Vulnerability Score: 0.2
