### ISSUE TITLE
Reduce sensitivity of mouse wheel zoom

### ISSUE THREAD

**Issue by Skerre** [SDG-AI-Lab/DSVI_Tool_v3#88]
The mouse wheel zoom is too strong, so it would be good to reduce the intensity so it does not zoom too much.

**Comment by lordakarias** [comment]
The sensitivity looks ok on my screen. Can you please elaborate more on this?
https://user-images.githubusercontent.com/3380109/193829935-54201f25-b880-4f7c-a302-d0a23adfe48e.mp4

**Comment by Skerre** [comment]
Hi Zekarias,

ok in my case it jumps a lot more. Maybe its related to my OS system settings then.

**Comment by Skerre** [comment]
@lordakarias I would then move to some other issues, as the ones I suggested in the mail or please have a look at the tracker:

https://github.com/SDG-AI-Lab/DSVI_Tool_v3/projects/1

Thank you!
